Update bin/add-exercise

diff --git a/bin/add-exercise b/bin/add-exercise
--- a/bin/add-exercise
+++ b/bin/add-exercise
@@ -1,38 +1,87 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+# Synopsis:
+# Scaffold the files for a new practice exercise.
+# After creating the exercise, follow the instructions in the output.
 
-if [ $# -ne 1 ]; then
-    echo "Usage: bin/add-exercise <exercise-slug>"
+# Example:
+# bin/add-exercise two-fer
+
+# Example with difficulty:
+# bin/add-exercise -d 5 two-fer
+
+# Example with author and difficulty:
+# bin/add-exercise -a foo -d 3 two-fer
+
+set -euo pipefail
+scriptname=$0
+
+help_and_exit() {
+    echo >&2 "Scaffold the files for a new practice exercise."
+    echo >&2 "Usage: ${scriptname} [-h] [-a author] [-d difficulty] <exercise-slug>"
+    echo >&2 "Where: author is the GitHub username of the exercise creator."
+    echo >&2 "Where: difficulty is between 1 (easiest) to 10 (hardest)."
     exit 1
+}
+
+die() { echo >&2 "$*"; exit 1; }
+
+required_tool() {
+    command -v "${1}" >/dev/null 2>&1 ||
+        die "${1} is required but not installed. Please install it and make sure it's in your PATH."
+}
+
+require_files_template() {
+    jq -e --arg key "${1}" '.files[$key] | length > 0' config.json > /dev/null ||
+        die "The '.files.${1}' array in the 'config.json' file is empty. Please add at least one file. See https://exercism.org/docs/building/tracks/config-json#h-files for more information."
+}
+
+required_tool jq
+
+require_files_template "solution"
+require_files_template "test"
+require_files_template "example"
+
+[[ -f ./bin/fetch-configlet ]] || die "Run this script from the repo's root directory."
+
+author=''
+difficulty='4'
+while getopts :ha:d: opt; do
+    case $opt in
+        h) help_and_exit ;;
+        a) author=$OPTARG ;;
+        d) difficulty=$OPTARG ;;
+        ?) echo >&2 "Unknown option: -$OPTARG"; help_and_exit ;;
+    esac
+done
+shift "$((OPTIND - 1))"
+
+(( $# >= 1 )) || help_and_exit
+
+slug="${1}"
+
+if [[ -z "${author}" ]]; then
+    read -rp 'Your GitHub username: ' author
 fi
 
-command -v jq >/dev/null 2>&1 || {
-    echo >&2 "jq is required but not installed. Please install it and make sure it's in your PATH."
-    exit 1
-}
-command -v curl >/dev/null 2>&1 || {
-    echo >&2 "curl is required but not installed. Please install it and make sure it's in your PATH."
-    exit 1
-}
+./bin/fetch-configlet
+./bin/configlet create --practice-exercise "${slug}" --author "${author}" --difficulty "${difficulty}"
 
-bin/fetch-configlet
-
-# Add entry for exercise in config.json
-slug="${1}"
-# shellcheck disable=SC2001
-name=$(echo "${slug}" | sed 's/\b\w/\u&/g')
-uuid=$(bin/configlet uuid)
-jq --arg slug "${slug}" --arg uuid "${uuid}" --arg name "${name}" \
-    '.exercises.practice += [{slug: $slug, name: $name, uuid: $uuid, practices: [], prerequisites: [], difficulty: 1}]' \
-    config.json | sed 's/"average_run_time": 5/"average_run_time": 5.0/' > config.json.tmp && mv config.json.tmp config.json
-
-# Sync the exercise
-bin/configlet sync --update --yes --tests include --filepaths --metadata --docs --exercise "${slug}"
+filter='.exercises.practice = (.exercises.practice | sort_by(.difficulty, .slug))'
+jq "${filter}" config.json > config.sorted && mv config.sorted config.json
 
 exercise_dir="exercises/practice/${slug}"
-exercise_files=$(jq -r '.files[][]' "${exercise_dir}/.meta/config.json")
+files=$(jq -r --arg dir "${exercise_dir}" '.files | to_entries | map({key: .key, value: (.value | map("'"'"'" + $dir + "/" + . + "'"'"'") | join(" and "))}) | from_entries' "${exercise_dir}/.meta/config.json")
 
-for file in ${exercise_files}; do
-    touch "${exercise_dir}/${file}"
-done
+cat << NEXT_STEPS
+
+Your next steps are:
+- Create the test suite in $(jq -r '.test' <<< "${files}")
+  - The tests should be based on the canonical data at 'https://github.com/exercism/problem-specifications/blob/main/exercises/${slug}/canonical-data.json'
+  - Any test cases you don't implement, mark them in 'exercises/practice/${slug}/.meta/tests.toml' with "include = false"
+- Create the example solution in $(jq -r '.example' <<< "${files}")
+- Verify the example solution passes the tests by running 'bin/run-tests ${slug}'
+- Create the stub solution in $(jq -r '.solution' <<< "${files}")
+- Update the 'difficulty' value for the exercise's entry in the 'config.json' file in the repo's root
+- Validate CI using 'bin/configlet lint' and 'bin/configlet fmt'
+NEXT_STEPS
